services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1"]
      interval: 2s
      timeout: 2s
      retries: 20

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_started
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "8443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception: